export {default as Home} from './Home/Home'
export {default as MoreRandom} from './MoreRandom/MoreRandom'
export {default as SearchRecipe} from './SearchRecipe/Search'
export {default as Weekly} from './Weekly/Weekly'
export {default as DetailedRecipe} from './DetailedRecipe/DetailedRecipe'